# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('correo', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
