# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_persona_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='/photos'),
        ),
    ]
