# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 20:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_auto_20161127_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ref_person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='example.Persona'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
