# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 21:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0009_auto_20161127_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='persona', to=settings.AUTH_USER_MODEL),
        ),
    ]
