# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0010_auto_20161127_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ref_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_persona', to='example.Persona'),
        ),
    ]
