# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0011_auto_20161127_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
