# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-28 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0012_persona_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='phone',
        ),
    ]
