# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:01
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0013_remove_persona_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='image',
            field=cloudinary.models.CloudinaryField(default=0, max_length=255, verbose_name='photos'),
            preserve_default=False,
        ),
    ]
